version: '3.7'

services:
  db:
    image: postgres:16
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    env_file:
      - Back/.env
    ports:
      - "5432:5432"
    networks:
      - my-network

  flask:
    container_name: app
    build: Back
    command:
      bash -c "flask db upgrade && python app.py"
    volumes:
      - .:/usr/src/app/back
    restart: on-failure:10
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my-network

  bot:
    container_name: bot
    build: Front
    volumes:
      - .:/usr/src/app/front
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network: