"""empty message

Revision ID: 8cb9d402ad91
Revises: 
Create Date: 2024-07-06 03:39:30.551553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb9d402ad91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('salaryFrom', sa.Integer(), nullable=False),
    sa.Column('salaryTo', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.String(length=350), nullable=False),
    sa.Column('responsibility', sa.String(length=350), nullable=False),
    sa.Column('alternate_url', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=70), nullable=True),
    sa.Column('timeDay', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vacancy')
    # ### end Alembic commands ###
